export const useProducts = () => {
  const products = [
    {
      id: 1,
      name: 'Organic Tomatoes',
      description: 'Fresh, ripe organic tomatoes harvested daily',
      price: 4.99,
      image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcccf?w=400&q=75',
      category: 'Vegetables',
      rating: 4.8,
      reviews: 124,
      badge: 'Fresh',
      badgeColor: 'bg-green-100 text-green-700',
      inStock: true,
    },
    {
      id: 2,
      name: 'Organic Carrots',
      description: 'Sweet orange carrots, perfect for cooking',
      price: 2.99,
      image: 'https://images.unsplash.com/photo-1589927961304-2ba53b17f21f?w=400&q=75',
      category: 'Vegetables',
      rating: 4.7,
      reviews: 98,
      badge: 'New',
      badgeColor: 'bg-blue-100 text-blue-700',
      inStock: true,
    },
    {
      id: 3,
      name: 'Organic Lettuce',
      description: 'Crisp, fresh green lettuce',
      price: 3.49,
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=75',
      category: 'Vegetables',
      rating: 4.6,
      reviews: 87,
      badge: null,
      badgeColor: '',
      inStock: true,
    },
    {
      id: 4,
      name: 'Bell Peppers',
      description: 'Colorful bell peppers, sweet and crisp',
      price: 3.99,
      image: 'https://images.unsplash.com/photo-1599599810690-7b8d55131a55?w=400&q=75',
      category: 'Vegetables',
      rating: 4.9,
      reviews: 156,
      badge: 'Popular',
      badgeColor: 'bg-yellow-100 text-yellow-700',
      inStock: true,
    },
    {
      id: 5,
      name: 'Organic Broccoli',
      description: 'Fresh green broccoli florets',
      price: 3.79,
      image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=75',
      category: 'Vegetables',
      rating: 4.5,
      reviews: 65,
      badge: null,
      badgeColor: '',
      inStock: true,
    },
    {
      id: 6,
      name: 'Spinach Bunch',
      description: 'Fresh organic spinach, nutrient-rich',
      price: 2.49,
      image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&q=75',
      category: 'Leafy Greens',
      rating: 4.7,
      reviews: 92,
      badge: null,
      badgeColor: '',
      inStock: true,
    },
    {
      id: 7,
      name: 'Fresh Cucumber',
      description: 'Refreshing and crispy cucumbers',
      price: 1.99,
      image: 'https://images.unsplash.com/photo-1612621776503-f922f52b3f1d?w=400&q=75',
      category: 'Vegetables',
      rating: 4.6,
      reviews: 78,
      badge: 'Sale',
      badgeColor: 'bg-red-100 text-red-700',
      inStock: true,
    },
    {
      id: 8,
      name: 'Organic Beans',
      description: 'Fresh green beans, tender and delicious',
      price: 3.29,
      image: 'https://images.unsplash.com/photo-1599599810974-f77debf97c18?w=400&q=75',
      category: 'Vegetables',
      rating: 4.4,
      reviews: 54,
      badge: null,
      badgeColor: '',
      inStock: false,
    },
  ]

  const categories = ['All', 'Vegetables', 'Leafy Greens', 'Fruits', 'Root Vegetables']

  const featured = products.slice(0, 4)

  return {
    products,
    categories,
    featured,
  }
}
