export interface Product {
  id: number
  name: string
  category: string
  price: number
  unit: string
  emoji: string
  image: string
  rating: number
  reviews: number
  description: string
  badge?: string
  badgeColor?: string
  origin: string
  inStock: boolean
  featured?: boolean
}

export function useProducts() {
  const products: Product[] = [
    {
      id: 1,
      name: 'Organic Broccoli',
      category: 'Vegetables',
      price: 3.49,
      unit: 'per head',
      emoji: '🥦',
      image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=360&q=75',
      rating: 4.8,
      reviews: 124,
      description: 'Crisp, dark-green crowns bursting with vitamins. Harvested at peak freshness.',
      badge: 'Organic',
      badgeColor: 'bg-leaf-10 text-leaf',
      origin: 'Local Farm, 12 mi',
      inStock: true,
      featured: true,
    },
    {
      id: 2,
      name: 'Heirloom Tomatoes',
      category: 'Fruits',
      price: 5.99,
      unit: 'per lb',
      emoji: '🍅',
      image: 'https://images.unsplash.com/photo-1582284540020-8acbe03f4924?w=360&q=75',
      rating: 4.9,
      reviews: 89,
      description: 'Rainbow of flavors — sweet to tangy. Perfect for salads and sauces.',
      badge: 'Best Seller',
      badgeColor: 'bg-gold-20 text-earth',
      origin: 'Sunrise Valley, 8 mi',
      inStock: true,
      featured: true,
    },
    {
      id: 3,
      name: 'Baby Spinach',
      category: 'Greens',
      price: 3.99,
      unit: 'per 5oz bag',
      emoji: '🌿',
      image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=360&q=75',
      rating: 4.7,
      reviews: 67,
      description: 'Tender young leaves, triple-washed and ready to eat. Packed with iron.',
      badge: 'Fresh Cut',
      badgeColor: 'bg-sage-20 text-forest',
      origin: 'Green Acres, 5 mi',
      inStock: true,
    },
    {
      id: 4,
      name: 'Rainbow Carrots',
      category: 'Root Vegetables',
      price: 2.99,
      unit: 'per bunch',
      emoji: '🥕',
      image: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?w=360&q=75',
      rating: 4.6,
      reviews: 103,
      description: 'Purple, yellow & orange varieties with a satisfying crunch and natural sweetness.',
      origin: 'Root Farm Co., 15 mi',
      inStock: true,
      featured: true,
    },
    {
      id: 5,
      name: 'Purple Cauliflower',
      category: 'Vegetables',
      price: 4.49,
      unit: 'per head',
      emoji: '🫛',
      image: 'https://images.unsplash.com/photo-1510627498534-cf7e9002facc?w=360&q=75',
      rating: 4.5,
      reviews: 41,
      description: 'Striking purple hue with a slightly nutty flavor. Rich in antioxidants.',
      badge: 'Rare Find',
      badgeColor: 'bg-purple-100 text-purple-700',
      origin: 'Heritage Fields, 20 mi',
      inStock: true,
    },
    {
      id: 6,
      name: 'English Cucumbers',
      category: 'Vegetables',
      price: 1.99,
      unit: 'each',
      emoji: '🥒',
      image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=360&q=75',
      rating: 4.4,
      reviews: 88,
      description: 'Long, thin-skinned and seedless. Crisp, refreshingly mild.',
      origin: 'Crystal Greenhouse, 3 mi',
      inStock: true,
    },
    {
      id: 7,
      name: 'Sweet Bell Peppers',
      category: 'Vegetables',
      price: 4.29,
      unit: 'per 3-pack',
      emoji: '🫑',
      image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=360&q=75',
      rating: 4.8,
      reviews: 76,
      description: 'Red, yellow & orange trio. Naturally sweet and high in vitamin C.',
      badge: 'Value Pack',
      badgeColor: 'bg-orange-100 text-orange-700',
      origin: 'Sunshine Farm, 10 mi',
      inStock: true,
    },
    {
      id: 8,
      name: 'Zucchini',
      category: 'Vegetables',
      price: 2.49,
      unit: 'per lb',
      emoji: '🥬',
      image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=360&q=75',
      rating: 4.3,
      reviews: 55,
      description: 'Versatile summer squash. Great for grilling, spiralizing or baking.',
      origin: 'Valley Gardens, 7 mi',
      inStock: true,
    },
    {
      id: 9,
      name: 'Fresh Garlic',
      category: 'Aromatics',
      price: 1.79,
      unit: 'per bulb',
      emoji: '🧄',
      image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=360&q=75',
      rating: 4.9,
      reviews: 211,
      description: 'Plump, pungent cloves grown without pesticides. Pure, intense flavor.',
      badge: 'Fan Favorite',
      badgeColor: 'bg-gold-20 text-earth',
      origin: 'Aromas Family Farm, 18 mi',
      inStock: true,
    },
    {
      id: 10,
      name: 'Sweet Corn',
      category: 'Grains',
      price: 0.99,
      unit: 'per ear',
      emoji: '🌽',
      image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=360&q=75',
      rating: 4.7,
      reviews: 143,
      description: 'Picked at peak sweetness. Best eaten the same day for maximum flavor.',
      badge: 'In Season',
      badgeColor: 'bg-yellow-100 text-yellow-800',
      origin: 'Meadow Hill, 4 mi',
      inStock: true,
      featured: true,
    },
    {
      id: 11,
      name: 'Portobello Mushrooms',
      category: 'Fungi',
      price: 5.49,
      unit: 'per pack',
      emoji: '🍄',
      image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=360&q=75',
      rating: 4.6,
      reviews: 62,
      description: 'Meaty caps perfect for grilling or stuffing. Earthy, rich umami flavor.',
      origin: 'Fog Valley Mushrooms, 2 mi',
      inStock: true,
    },
    {
      id: 12,
      name: 'Red Onions',
      category: 'Aromatics',
      price: 1.49,
      unit: 'per lb',
      emoji: '🧅',
      image: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=360&q=75',
      rating: 4.5,
      reviews: 99,
      description: 'Mild and slightly sweet raw. Caramelizes beautifully when cooked.',
      origin: 'Heritage Farm, 12 mi',
      inStock: false,
    },
  ]

  const categories = ['All', ...new Set(products.map(p => p.category))]
  const featured = products.filter(p => p.featured)

  return { products, categories, featured }
}